### ISSUE TITLE
56對偏鄉地區沒用

### ISSUE THREAD

**Issue by aiueoH** [GeorgioWan/TopGunPoke.js#1]
建議抓 pkget 的通知

**Comment by GeorgioWan** [comment]
感謝您的寶貴建議，**TopGun56** 更名為 **TopGunPoke** 並支援 **pkget** 囉 :tada::tada:

[Check this](https://github.com/GeorgioWan/TopGunPoke.js/commit/a609e93590479aa9ded2e17c6949c835cfb211ef)
